#!/usr/bin/env python


def main(argv=None):
    import sys
    import haml

    if argv is None:
        argv = sys.argv[1:]

    from argparse import ArgumentParser, FileType
    parser = ArgumentParser()
    parser.add_argument('input', type=FileType('r'), help='input file')
    parser.add_argument('-o',
                        '--output',
                        type=FileType('w'),
                        default=sys.stdout,
                        help='File to write to')
    args = parser.parse_args(argv)

    data = args.input.read()
    args.output.write(haml.preprocessor(data))


if __name__ == "__main__":
    main()
