#!/usr/bin/env python

import sys
import haml


def render(data):
    from mako.template import Template
    from mako.lookup import TemplateLookup

    lookup = TemplateLookup(["."], preprocessor=haml.preprocessor)
    template = Template(data, lookup=lookup, preprocessor=haml.preprocessor)
    return template.render()


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    from argparse import ArgumentParser, FileType
    parser = ArgumentParser()
    parser.add_argument('input', type=FileType('r'), help='input file')
    parser.add_argument('-o',
                        '--output',
                        type=FileType('w'),
                        default=sys.stdout,
                        help='File to write to')
    args = parser.parse_args(argv)

    haml_txt = args.input.read()
    html_txt = render(haml_txt)
    args.output.write(html_txt)


if __name__ == "__main__":
    main()
